# Autogenerated wrapper script for TtH_jll for x86_64-w64-mingw32
export tth

JLLWrappers.@generate_wrapper_header("TtH")
JLLWrappers.@declare_executable_product(tth)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        tth,
        "bin/tth.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
